import request from './request'

export const sendPrivateMsg = (data) => request.post('/api/chat/private/send', data)
export const getPrivateHistory = (params) => request.get('/api/chat/private/history', { params })
export const sendTeamMsg = (data) => request.post('/api/chat/team/send', data)
export const getTeamHistory = (params) => request.get('/api/chat/team/history', { params })
export const editMsg = (data) => request.post('/api/chat/message/edit', data)
export const revokeMsg = (msgId) => request.post('/api/chat/message/revoke', { msgId })
export const readMsgs = (data) => request.post('/api/chat/message/read', data)
export const getUnreadCount = () => request.get('/api/chat/unread-count')
export const collectMsg = (data) => request.post('/api/chat/message/collect', data)
export const cancelCollect = (collectionId) => request.delete(`/api/chat/message/collect/${collectionId}`)
export const getCollections = (params) => request.get('/api/chat/message/collections', { params })
export const pinMsg = (data) => request.post('/api/chat/message/pin', data)
export const unpinMsg = (pinId) => request.delete(`/api/chat/message/pin/${pinId}`)
export const getPinList = (params) => request.get('/api/chat/message/pins', { params })
export const searchMsg = (params) => request.get('/api/chat/message/search', { params })
export const reportMessage = (data) => request.post('/api/chat/message/report', data)
export const getMessageReportStatus = (reportId) => request.get(`/api/chat/message/report/${reportId}`)
export const getAdminMessageReportContext = (reportId) => request.get(`/api/chat/message/report/admin/${reportId}/context`)
export const getAdminMessageReportList = (params) => request.get('/api/chat/message/report/admin/list', { params })
export const handleAdminMessageReport = (data) => request.post('/api/chat/message/report/admin/handle', data)
export const appealMessageReport = (reportId) => request.post(`/api/chat/message/report/${reportId}/appeal`)
export const getGroupNotice = (params) => request.get('/api/chat/group/notice', { params })
export const setGroupNotice = (data) => request.post('/api/chat/group/notice', data)
export const groupMuteAllCompat = (data) => request.post('/api/chat/group/mute-all', data)
export const groupMuteMemberCompat = (data) => request.post('/api/chat/group/mute-member', data)
export const groupUnmuteMemberCompat = (data) => request.post('/api/chat/group/unmute-member', data)
export const groupRenameCompat = (data) => request.post('/api/chat/group/name', data)
